[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mav"
version = "0.1.0"
description = "Multi-Agent Vulnerable System"
dependencies = [
    "python-dotenv",
]

[tool.setuptools]
packages = ["mav"]
package-dir = {"" = "src"}